DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS sessions;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  dob INTEGER,
  street TEXT,
  zip INTEGER
);

CREATE TABLE sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userid INTEGER UNIQUE NOT NULL,
    session TEXT
);
